# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-01 12:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term1', models.IntegerField()),
                ('term2', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub1', models.IntegerField()),
                ('sub2', models.IntegerField()),
                ('sub3', models.IntegerField()),
                ('sub4', models.IntegerField()),
                ('sub5', models.IntegerField()),
                ('sub6', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regNo', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('sex', models.CharField(choices=[(b'm', b'Male'), (b'f', b'Female'), (b'o', b'Others/Undefined')], max_length=1)),
                ('dob', models.DateField(max_length=16)),
                ('department', models.CharField(choices=[(b'CS', b'CS'), (b'CE', b'CE'), (b'PE', b'PE'), (b'ME', b'ME'), (b'EC', b'EC')], max_length=2)),
                ('usertype', models.CharField(choices=[(b'F', b'Faculty'), (b'S', b'Student')], max_length=10)),
                ('phoneNo', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='marks',
            name='regNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='regNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User'),
        ),
    ]
