# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-01 12:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Marks',
            new_name='Mark',
        ),
    ]
