# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-02 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170501_1211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mark',
            old_name='sub1',
            new_name='en14401',
        ),
        migrations.RenameField(
            model_name='mark',
            old_name='sub2',
            new_name='en14402',
        ),
        migrations.RenameField(
            model_name='mark',
            old_name='sub3',
            new_name='en14403',
        ),
        migrations.RenameField(
            model_name='mark',
            old_name='sub4',
            new_name='en14404',
        ),
        migrations.RenameField(
            model_name='mark',
            old_name='sub5',
            new_name='en14405',
        ),
        migrations.RenameField(
            model_name='mark',
            old_name='sub6',
            new_name='en14406',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='regNo',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
